name: CI Pipeline

on:
  pull_request:

concurrency: # Cancel in-progress pipelines on pull request update
  group: pr-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '10.x'
          run_install: false

      - name: Verify PNPM Cache Directory
        run: |
          PNPM_STORE_PATH="$( pnpm store path --silent )"
          if [ ! -d "$PNPM_STORE_PATH" ]; then
            echo "PNPM store directory does not exist, creating it."
            mkdir -p "$PNPM_STORE_PATH"
          else
            echo "PNPM store directory exists."
          fi

      - name: Setup package manager cache
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
      # - name: Cache pnpm dependencies
      #   id: cache-pnpm
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.pnpm-store
      #     key: pnpm-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
      #     restore-keys: |
      #       pnpm-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '10.x'
          run_install: false

      - name: Verify PNPM Cache Directory
        run: |
          PNPM_STORE_PATH="$( pnpm store path --silent )"
          if [ ! -d "$PNPM_STORE_PATH" ]; then
            echo "PNPM store directory does not exist, creating it."
            mkdir -p "$PNPM_STORE_PATH"
          else
            echo "PNPM store directory exists."
          fi

      - name: Setup package manager cache
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
      # - name: Cache pnpm dependencies
      #   id: cache-pnpm
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.pnpm-store
      #     key: pnpm-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
      #     restore-keys: |
      #       pnpm-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm test --passWithNoTests

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '10.x'
          run_install: false

      - name: Verify PNPM Cache Directory
        run: |
          PNPM_STORE_PATH="$( pnpm store path --silent )"
          if [ ! -d "$PNPM_STORE_PATH" ]; then
            echo "PNPM store directory does not exist, creating it."
            mkdir -p "$PNPM_STORE_PATH"
          else
            echo "PNPM store directory exists."
          fi

      - name: Setup package manager cache
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
      # - name: Cache pnpm dependencies
      #   id: cache-pnpm
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.pnpm-store
      #     key: pnpm-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
      #     restore-keys: |
      #       pnpm-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
